<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;



/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */

function manualsness_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    // Add content type suggestions.
    if (($node = \Drupal::request()->attributes->get('node')) && is_object($node)) {
        array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
    }


}